package controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.scene.control.PasswordField;
import javafx.scene.control.ProgressBar;
import javafx.scene.control.TextField;
import javafx.stage.DirectoryChooser;
import javafx.stage.FileChooser;
import javafx.stage.FileChooser.ExtensionFilter;
import javafx.stage.Stage;
import model.Musica;
import model.Player;
import model.Playlist;
import model.User;

public class PlayerSceneController {
	
	private Stage stage;
	private Scene scene;
	private Parent root;
	
	//player
	@FXML
	private Button playButton;
	@FXML
	private Label musicasLabel;
	@FXML
	private Label playlistAtualLabel;
	@FXML
	private ProgressBar progressBar;
	@FXML
	private Button pauseButton;
	@FXML
	private Button previousButton;
	@FXML
	private Button nextButton;
	@FXML
	private Button selectDirectoryButton;
	@FXML
	private Button selectFileButton;
	@FXML
	private Label Username;
	
	//login
	@FXML
	private Button exitButton;
	@FXML
	private TextField loginUserName;
	@FXML
	private PasswordField loginSenha;

	// Event Listener on Button[#playButton].onAction
	@FXML
	public void tocarMusica(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#pauseButton].onAction
	@FXML
	public void pausarMusica(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#previousButton].onAction
	@FXML
	public void prevMusica(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#nextButton].onAction
	@FXML
	public void nextMusica(ActionEvent event) {
		// TODO Autogenerated
	}
	@FXML
	public void selectArquivo(ActionEvent event) {
		FileChooser file_chooser = new FileChooser();
		file_chooser.setTitle("Selecione o arquivo a ser adicionado");
		
		FileChooser.ExtensionFilter fileExtensions = 
		new FileChooser.ExtensionFilter("Sound files", "*.mp3", "*.wav", "*.ogg");
		file_chooser.getExtensionFilters().add(fileExtensions);
		
		file_chooser.showOpenDialog(null);
	}
	@FXML
	public void selectDiretorio(ActionEvent event) {
		DirectoryChooser directory_chooser = new DirectoryChooser();
		directory_chooser.setTitle("Selecione o diretorio a ser adicionado");
		directory_chooser.showDialog(null);
	}
	@FXML
	public void fecharAplicação(ActionEvent event) {
		System.exit(0);
	}
	
	@FXML
	public void logar(ActionEvent event) {
		switchScene(event, "PlayerScene.fxml");
		
		User usuario = new User();
		usuario.setLogin(loginUserName.getText());
		usuario.setSenha(loginSenha.getText());
		definirUsuarioLogado(usuario);
		Username.setText(usuario.getLogin()); //Por algum motivo o setText não funciona, é como se Username fosse null.
	}
	
	public void switchScene(ActionEvent event, String SceneFile){
		try{
			root = FXMLLoader.load(getClass().getResource(SceneFile));
			stage = (Stage)((Node)event.getSource()).getScene().getWindow();
			scene = new Scene(root);
			stage.setScene(scene);
			stage.show();
		}
		catch (IOException e) {
			
		}
	}
	
private Player player;
	
	public PlayerSceneController() {
		this.player = new Player();
	}
	
	public void adicionarMusica(Musica musica) {
        player.addMusica(musica);
    }
	
	public void adicionarPlaylist(Playlist playlist) {
        player.addPlaylist(playlist);
    }
	
	public void adicionarDiretorio(String diretorio) {
        player.addDiretorio(diretorio);
    }
	
	public List<Playlist> obterPlaylists() {
        return player.getPlaylists();
    }
	
	public List<Musica> obterMusicas() {
        return player.getMusicas();
    }
	
	public List<String> obterDiretorios() {
        return player.getDiretorios();
    }
	
	public void definirUsuarioLogado(User usuario) {
        player.setUsuariologado(usuario);
    }
	
	public User obterUsuarioLogado() {
        return player.getUsuariologado();
    }
	
//	public void logarUsuario() {
//		
//	}
//	
//	public void cadastrarUsuario() throws IOException{
//		FileReader fr = new FileReader("template/usuarios");
//		BufferedReader br = new BufferedReader(fr);
//		String login;
//		while((login = br.readLine()) != null){
//			String senha = br.readLine();
//			User u = new User();
//			u.setLogin(login);
//			u.setSenha(senha);
//			player.addUsuario(u);
//		}
//	}
	
}
